### ISSUE TITLE
Adicionar mensagem para desafios não concluídos

### ISSUE THREAD

**Issue by Rrhapsod** [valdemirfilho/devexplorer#43]
Gostaria de adicionar uma mensagem indicativa caso o usuário não tenha colocado links dos seus desafios.

Antes:
![antes](https://user-images.githubusercontent.com/47695915/193968561-7c342d9e-2752-4130-bd20-42bc3c777a97.png)

Depois:
![depois](https://user-images.githubusercontent.com/47695915/193968595-2ab9e8e7-6ffd-4e4f-a02c-d22279f11eea.png)

**Comment by valdemirfilho** [comment]
Ok! Pode fazer! 🙂
